### PR TITLE
test: add test which emulates the error thrown in the simulation (issue #207)

### PR DESCRIPTION
**Pull request by angelacorte**
see issue #207

### CODE REVIEW

**Comment by angelacorte** [comment]
Note:
I don't think that the problem is the alignment of the `when`, because if we call `foo` outside `when` but inside `share`, it breaks anyway.

**Comment by DanySK** [comment]
when is it annotated first, and when is it annotated then? Copy the stacktraces

**Comment by angelacorte** [comment]
> when is it annotated first, and when is it annotated then? Copy the stacktraces

```
java.lang.IllegalStateException: Aggregate alignment clash by multiple aligned calls with the same path: PathImpl(path=[gradient.1, share.1, sharing.1, exchange.1, foo.1, neighboringViaExchange.1, exchange.1]).
The most likely cause is an aggregate function call within a loop
	at it.unibo.collektive.aggregate.api.impl.AggregateContext.exchanging(AggregateContext.kt:58)
	at it.unibo.collektive.aggregate.api.impl.AggregateContext.exchange(AggregateContext.kt:45)
	at it.unibo.collektive.aggregate.api.operators.AggregateOperatorsKt$neighboringViaExchange$1.invoke(AggregateOperators.kt:30)
	at it.unibo.collektive.aggregate.api.operators.AggregateOperatorsKt$neighboringViaExchange$1.invoke(AggregateOperators.kt:30)
	at it.unibo.collektive.aggregate.api.impl.AggregateContext.alignedOn(AggregateContext.kt:81)
	at it.unibo.collektive.aggregate.api.operators.AggregateOperatorsKt.neighboringViaExchange(AggregateOperators.kt:30)
	at it.unibo.collektive.aggregate.NestedCallsTest$1$foo$1.invoke(NestedCallsTest.kt:16)
```

**Comment by DanySK** [comment]
I mean **both** stacktraces, since you enter twice. One throws the exception, but there must be another

**Comment by angelacorte** [comment]
> I mean **both** stacktraces, since you enter twice. One throws the exception, but there must be another

the exception is thrown only in the second device, because on the first one it stops in the condition where the `localId == 0`, so `foo` is evaluated only in the else condition

**Comment by DanySK** [comment]
to trigger that exception, the control flow must enter the method with the same path **twice**. I want those two stacktraces (the latter is consequence of an exception, the former is not, and must be obtained through the debugger)

**Comment by angelacorte** [comment]
we have this path at first `path=[gradient.1, share.1, sharing.1, exchange.1, foo.1, neighboringViaExchange.1, exchange.1]`
with this stack trace https://pastebin.com/NAeJaaH4

then it iterates a second time creating this path `[gradient.1, share.1, sharing.1, exchange.1, project.1, neighboringViaExchange.1, exchange.1]`
and this stack trace https://pastebin.com/RRbbpYCk

last it has again this path `[gradient.1, share.1, sharing.1, exchange.1, foo.1, neighboringViaExchange.1, exchange.1]`
https://pastebin.com/XhdzU2Hp

**Pull request merged**
